dataset: libri-speech

paths:
  df:
    train: libri-speech-orig-train.csv
    val: libri-speech-orig-val.csv
    test: None
  mel-spectro:
    h5:
      train: LibriSpeech/libri-speech_mel-spectro_train_dB-80.h5
      val: LibriSpeech/libri-speech_mel-spectro_val_dB-80.h5
      test: None
      metadata:
        train: libri-speech_mel_spectro_metadata_train_dB-80.csv
        val: libri-speech_mel_spectro_metadata_val_dB-80.csv
        test: None

stats:
  mel-spectro:
    train:
      mean: -23.484376907348633
      std: 0.1036109030246734

transform:
  sample_rate: 16000
  n_mfcc: 40
  win_length: 400
  hop_length: 200
  n_fft: 512
  f_min: 0
  f_max: 8000
  n_mels: 80