dataset: timit

paths:
  base: /workspace/audio_data/TIMIT/AUDIO_FILES/ORIGINAL
  train: train
  val: train
  test: test

  df:
    train: timit-orig-train.csv
    val: timit-orig-val.csv
    test: timit-orig-test.csv

transform:
  sample_rate: 16000
  n_mfcc: 40
  win_length: 400
  hop_length: 200
  n_fft: 512
  f_min: 0
  f_max: 8000