dataset: timit

paths:
  df:
    train: timit-orig-train.csv
    val: timit-orig-val.csv
    test: timit-orig-test.csv
  speakers: timit-speakers.csv
  sentences: timit-sentences.csv
  raw:
    h5:
      train: TIMIT/timit_raw_train.h5
      val: TIMIT/timit_raw_valid.h5
      test: TIMIT/timit_raw_test.h5
      metadata:
        train: timit_raw_metadata_train.csv
        val: timit_raw_metadata_valid.csv
        test: timit_raw_metadata_test.csv
  mel-spectro:
    h5:
      train: TIMIT/timit_mel-spectro_train_dB-80.h5
      val: TIMIT/timit_mel-spectro_valid_dB-80.h5
      test: TIMIT/timit_mel-spectro_test_dB-80.h5
      metadata:
        train: timit_mel_spectro_metadata_train_dB-80.csv
        val: timit_mel_spectro_metadata_valid_dB-80.csv
        test: timit_mel_spectro_metadata_test_dB-80.csv

stats:
  raw:
    train:
      mean: 0.00000020026256208893756
      std: 0.004097380209714174
  mel-spectro:
    train:
      mean: -33.92084503173828
      std: 0.08098893612623215

transform:
  sample_rate: 16000
  n_mfcc: 40
  win_length: 400
  hop_length: 200
  n_fft: 512
  f_min: 0
  f_max: 8000
  n_mels: 80