dataset: timit

paths:
  df:
    train: timit-orig-train.csv
    val: timit-orig-val.csv
    test: timit-orig-test.csv
  h5:
    train: TIMIT/timit_mfcc_train.h5
    val: TIMIT/timit_mfcc_valid.h5
    test: TIMIT/timit_mfcc_test.h5
    metadata:
      train: timit_metadata_train.csv
      val: timit_metadata_valid.csv
      test: timit_metadata_test.csv

transform:
  sample_rate: 16000
  n_mfcc: 40
  win_length: 400
  hop_length: 200
  n_fft: 512
  f_min: 0
  f_max: 8000