dataset: vox2

paths:
  df:
    train: vox2-orig-train.csv
    val: vox2-orig-val.csv
    test: vox2-orig-test.csv

transform:
  sample_rate: 16000
  n_mfcc: 40
  win_length: 400
  hop_length: 200
  n_fft: 512
  f_min: 0
  f_max: 8000