mode: train # either train or eval
use_wandb: True

# Environment
env:
  world_size: 1 # number of GPUs to run a batch in parallel

# Mask MFCC
masking:
  position: end # end, beginning or center
  n_frames: 60 # max. number of input frames
  k_frames: 60 # number of frames to predict
  start_idx: sliding-window # beginning (first n+k frames affected per file), random (n+k frames at random position per file), sliding-window (first n+k frames, then shift by n+k -> multiple frames per file)

# Dataset
data:
  config_file: datasets/timit-original.yaml

# Training settings
train:
  batch_size: 32
  max_number_of_epochs: 300
  early_stopping: False

# LR Scheduler
lr_scheduler:
  activate: True
  step_size: 10
  gamma: 0.8

# Optimizer
optimizer:
  type: adam
  weight_decay: 0.0001