title: Speech Prediction
description: A Deep Learning Model to predict the subsequent frames of Mel-spectrograms
lang: en

# Site settings
url: https://sagerpascal.github.io/speech-prediction/
baseurl: /temporal-speech-context
site_author: Pascal Sager
repo_url: https://github.com/sagerpascal/speech-prediction

# local theme
#theme: jekyll-rtd-theme
#debug:
#  compress: false
#  dist: true
#  shortcodes: true

# remote theme
remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
- Gemfile
- Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions



