title: Temporal Speech Context
description: A neural network to predict a frame of speech (MFCC) from its predecessor
lang: en

# Site settings
url: https://sagerpascal.github.io/temporal-speech-context/
baseurl: /temporal-speech-context
site_author: Pascal Sager
repo_url: https://github.com/sagerpascal/temporal-speech-context

# local theme
theme: jekyll-rtd-theme
#debug:
#  compress: false
#  dist: true
#  shortcodes: true

# remote theme
#remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
- Gemfile
- Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions



