mode: train # either train or evaluate
dataset: torch-speech-commands
use_wandb: False

# Training settings
max_number_of_epochs: 30
early_stopping: False

# LR Scheduler
use_lr_scheduler: False
scheduler_step_size: 20
scheduler_gamma: 0.1

# Optimizer
optimizer: adam
weight_decay: 0.0001