mode: train # either train or eval
use_wandb: False

# Mask MFCC
masking:
  position: end # end, beginning or random
  n_frames: 81

data:
  dataset: torch-speech-commands # torch-speech-commands, TIMIT, VOX2
  subset: 00_ORIGINAL
  audio_list_train: 02_train
  audio_list_val: 03_val
  dataset_path: /scratch/xnur/DATASETS

# Training settings
train:
  batch_size: 64
  max_number_of_epochs: 40
  early_stopping: False

# LR Scheduler
lr_scheduler:
  activate: False
  step_size: 10
  gamma: 0.3

# Optimizer
optimizer:
  type: adam
  weight_decay: 0.0001